x-global-config: &global-config
  logging:
    driver: json-file
    options:
      max-size: 50m
  restart: always

services:
  pool:
    build: pool
    network_mode: "host"
    ports:
      - "3448:3448"
      - "80:80"
    depends_on:
      redis:
        condition: service_started
    <<: *global-config

  redis:
    image: redis:alpine
    network_mode: "host"
    <<: *global-config
